name: "nodejs-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /src/logs/error/*.log
    - /src/logs/warn/*.log
    - /src/logs/info/*.log
  fields:
    - service: nodejs
  fields_under_root: true
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'


output.logstash:
  hosts: ["13.235.47.147:5044"]
