version: '3'
services:
  nodejs:
    build:
      context: .
    volumes:
      - type: volume
        source: log-data
        target: /var/log/server
    ports:
      - "4003:4003"

  filebeat:
    build:
      context: ./filebeat
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        
      - type: volume
        source: log-data
        target: /var/log/server
    networks:
      - elk
    depends_on:
      - logstash
volumes:
  log-data: