version: '3'
services:
  nodejs:
    build: .
    ports:
      - "4003:4003"


  filebeat:
    build:
      context: ./filebeat
    volumes:
      - /logs:/logs
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

       