version: '3'

services:
 
  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
        - ./logs:/src/logs


  nodejs:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "4003:4003"
    volumes:
        - /logs:/src/logs