version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: log-data
        target: /app/logs
    ports:
      - "4003:4003"

  filebeat:
    build:
      context: ./filebeat
    volumes:
      - type: bind
        source: ./filebeat/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
      - type: volume
        source: log-data
        target: /var/log/server

volumes:
  log-data:
