version: '3'

services:
 
  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
        - ./nodejs-logs:/src/logs
    depends_on:
        - elasticsearch
        - kibana

  nodejs:
    build:
      context: ./nodejs-app 
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    volumes:
        - ./nodejs-logs:/src/logs